### ISSUE TITLE
shreddit fails to run

### ISSUE THREAD

**Issue by telometto** [pythonInRelay/Shreddit#11]
I'm using Fedora 35, which comes with python 3.10 by default. Using the command `python setup.py install` does not work, since `install` is deprecated; using `python setup.py build` works, but running `shreddit -c /path/to/praw.ini` results in the following output:
```sh
Traceback (most recent call last):
  File "/home/MYUSER/.local/bin/shreddit", line 8, in <module>
    sys.exit(main())
  File "/home/MYUSER/.local/lib/python3.10/site-packages/shreddit/app.py", line 39, in main
    user_config = yaml.safe_load(fh)
  File "/home/MYUSER/.local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/home/MYUSER/.local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/MYUSER/.local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/MYUSER/.local/lib/python3.10/site-packages/yaml/composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/home/MYUSER/.local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/MYUSER/.local/lib/python3.10/site-packages/yaml/parser.py", line 171, in parse_document_start
    raise ParserError(None, None,
yaml.parser.ParserError: expected '<document start>', but found '<scalar>'
  in "praw.ini", line 4, column 1
```

How can I fix this?

**Comment by pythonInRelay** [comment]
Follow the instructions.
