### ISSUE TITLE
Cannot run Shreddit outside the directory with praw.ini in it

### ISSUE THREAD

**Issue by amitai** [pythonInRelay/Shreddit#12]
This came up because I'm trying to pop this into a cron job.  

```bash

user@rikki ~ $ shreddit --config /home/user/Dropbox/ProgramSettings/Shreddit/shreddit.yml
Traceback (most recent call last):
  File "/home/user/.local/bin/shreddit", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python2.7/site-packages/shreddit/app.py", line 44, in main
    shredder = Shredder(default_config, args.user)
  File "/home/user/.local/lib/python2.7/site-packages/shreddit/shredder.py", line 28, in __init__
    self._connect()
  File "/home/user/.local/lib/python2.7/site-packages/shreddit/shredder.py", line 80, in _connect
    self._r = praw.Reddit(self._user, check_for_updates=False, user_agent="python:shreddit:v6.0.4")
  File "/home/user/.local/lib/python2.7/site-packages/praw/reddit.py", line 129, in __init__
    self.config = Config(config_section, **config_settings)
  File "/home/user/.local/lib/python2.7/site-packages/praw/config.py", line 66, in __init__
    self.custom = dict(Config.CONFIG.items(site_name), **settings)
  File "/usr/lib/python2.7/ConfigParser.py", line 347, in items
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'default'
You provided the name of a praw.ini configuration which does not exist.

For help with creating a Reddit instance, visit
https://praw.readthedocs.io/en/latest/code_overview/reddit_instance.html

For help on configuring PRAW, visit
https://praw.readthedocs.io/en/latest/getting_started/configuration.html
user@rikki ~ $ cd Dropbox/ProgramSettings/Shreddit/
user@rikki ~/Dropbox/ProgramSettings/Shreddit $ shreddit --config /home/user/Dropbox/ProgramSettings/Shreddit/shreddit.yml
INFO:shreddit:Logged in as redditusername.
INFO:shreddit:Deleting ALL items before 2022-01-27T11:51:59.868510-05:00
INFO:shreddit:Deleting items not whitelisted until 2022-02-16T07:51:59.868079-05:00
INFO:shreddit:Ignoring ALL items after 2022-02-16T07:51:59.868079-05:00
INFO:shreddit:Targeting overview sorted by new
INFO:shreddit:Loading items to delete...
INFO:shreddit:Done. Starting on batch of 5 items...
INFO:shreddit:Finished deleting 0 items. 
user@rikki ~/Dropbox/ProgramSettings/Shreddit $ 

```

You can see when I run the command from ~ it fails, can't find praw.ini. When I go to the directory that has praw.ini in it, the same command works. 

Is it possible I need to point to the praw.ini file in the command, or that I need to add something in the shreddit.yml file to reference the praw.ini file?

**Comment by pythonInRelay** [comment]
You are running shreddit from your home directory `~` the first thing it does is load the .yml you specified but then it cannot find the next file that it needs because you are in a different directory.

run the script from the directory to which you cloned shreddit. This is not a bug.
