### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections' (D:\Python\lib\collections\__init__.py)

### ISSUE THREAD

**Issue by thiccyoshi4568** [pythonInRelay/Shreddit#13]
Just installed this fork of Shreddit, and installation was good until running the shreddit command results in this. Any help?

Traceback (most recent call last):
  File "D:\Python\Scripts\shreddit-script.py", line 33, in <module>
    sys.exit(load_entry_point('shreddit==6.0.7', 'console_scripts', 'shreddit')())
  File "D:\Python\Scripts\shreddit-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "D:\Python\lib\importlib\metadata\__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "D:\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Python\lib\site-packages\shreddit\app.py", line 9, in <module>
    from shreddit.shredder import Shredder
  File "D:\Python\lib\site-packages\shreddit\shredder.py", line 6, in <module>
    import praw
  File "D:\Python\lib\site-packages\praw\__init__.py", line 14, in <module>
    from .reddit import Reddit  # NOQA
  File "D:\Python\lib\site-packages\praw\reddit.py", line 11, in <module>
    from prawcore import (Authorizer, DeviceIDAuthorizer, ReadOnlyAuthorizer,
  File "D:\Python\lib\site-packages\prawcore\__init__.py", line 4, in <module>
    from .auth import (Authorizer, DeviceIDAuthorizer, ReadOnlyAuthorizer,  # NOQA
  File "D:\Python\lib\site-packages\prawcore\auth.py", line 5, in <module>
    from requests import Request
  File "D:\Python\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "D:\Python\lib\site-packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "D:\Python\lib\site-packages\urllib3\connectionpool.py", line 29, in <module>
    from .connection import (
  File "D:\Python\lib\site-packages\urllib3\connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "D:\Python\lib\site-packages\urllib3\util\__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "D:\Python\lib\site-packages\urllib3\util\connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "D:\Python\lib\site-packages\urllib3\util\wait.py", line 1, in <module>
    from .selectors import (
  File "D:\Python\lib\site-packages\urllib3\util\selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (D:\Python\lib\collections\__init__.py)

**Comment by kusold** [comment]
I am also seeing this when trying to run shreddit inside a `python:alpine` (maps to [3.10.4-alpine3.15](https://github.com/docker-library/python/blob/f871d0435e7f35a693fa1b60aa159e6a1a4c6a2e/3.10/alpine3.15/Dockerfile)) container.

I eventually found a comment ( https://github.com/psf/requests/issues/5901#issuecomment-895802019 ) pointing out that urllib3 is very old.

I have a branch where I bumped:
* urllib -> latest (solves this issue)
* requests -> latest (due to urllib bump)
* pyyaml -> latest (also incompatible with the latest version of python)
* praw & prawcore (might as well)

I'm testing this code out now. If everything still works I'll submit a PR.
