### ISSUE TITLE
Multiple errors on install, some of them due to a typo in your instructions; an error, on run, that ended with 'invalid syntax'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [pythonInRelay/Shreddit#4]
Please see the following. I am on Mint 20 Cinnamon.

```
[redactedUsername]@x1 ~/[redacted]/shreddit/Shreddit $ apt install python-pip
[sudo] password for [redactedUsername]: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-pip
[redactedUsername]@x1 ~/[redacted]/shreddit/Shreddit $ sudo apt install python-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-pip
[redactedUsername]@x1 ~/[redacted]/shreddit/Shreddit $ pip install --updgrade pip

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --updgrade
[redactedUsername]@x1 ~/[redacted]/shreddit/Shreddit $ # Note the 'updgrade' (*sic*) - that is your typo.
[redactedUsername]@x1 ~/[redacted]/shreddit/Shreddit $ pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /home/[redactedUsername]/.local/lib/python3.8/site-packages (21.0.1)
[redactedUsername]@x1 ~/[redacted]/shreddit/Shreddit $ # git clone done already
[redactedUsername]@x1 ~/[redacted]/shreddit/Shreddit $ ls
build  LICENSE      praw.ini.example  requirements.txt  setup.py  shreddit.egg-info  shreddit.yml.example
dist   MANIFEST.in  README.md         setup.cfg         shreddit  shreddit.yml
[redactedUsername]@x1 ~/[redacted]/shreddit/Shreddit $ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: decorator==4.0.10 in /home/[redactedUsername]/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (4.0.10)
Requirement already satisfied: wheel==0.24.0 in /home/[redactedUsername]/.local/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (0.24.0)
Requirement already satisfied: appdirs==1.4.3 in /home/[redactedUsername]/.local/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (1.4.3)
Requirement already satisfied: arrow==0.10.0 in /home/[redactedUsername]/.local/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (0.10.0)
Requirement already satisfied: backports-abc==0.5 in /home/[redactedUsername]/.local/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (0.5)
Requirement already satisfied: certifi==2017.4.17 in /home/[redactedUsername]/.local/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (2017.4.17)
Requirement already satisfied: chardet==3.0.4 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 7)) (3.0.4)
Requirement already satisfied: idna==2.5 in /home/[redactedUsername]/.local/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (2.5)
Requirement already satisfied: praw==5.0.0 in /home/[redactedUsername]/.local/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (5.0.0)
Requirement already satisfied: prawcore==0.11.0 in /home/[redactedUsername]/.local/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (0.11.0)
Requirement already satisfied: python-dateutil==2.6.0 in /home/[redactedUsername]/.local/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (2.6.0)
Requirement already satisfied: PyYAML==3.12 in /home/[redactedUsername]/.local/lib/python3.8/site-packages (from -r requirements.txt (line 12)) (3.12)
Requirement already satisfied: requests==2.18.1 in /home/[redactedUsername]/.local/lib/python3.8/site-packages (from -r requirements.txt (line 13)) (2.18.1)
Requirement already satisfied: shreddit==6.0.7 in /home/[redactedUsername]/.local/lib/python3.8/site-packages (from -r requirements.txt (line 14)) (6.0.7)
Requirement already satisfied: six==1.12 in /home/[redactedUsername]/.local/lib/python3.8/site-packages (from -r requirements.txt (line 15)) (1.12.0)
Requirement already satisfied: tornado==4.5.1 in /home/[redactedUsername]/.local/lib/python3.8/site-packages (from -r requirements.txt (line 16)) (4.5.1)
Requirement already satisfied: update-checker==0.16 in /home/[redactedUsername]/.local/lib/python3.8/site-packages (from -r requirements.txt (line 17)) (0.16)
Requirement already satisfied: urllib3==1.21.1 in /home/[redactedUsername]/.local/lib/python3.8/site-packages (from -r requirements.txt (line 18)) (1.21.1)
[redactedUsername]@x1 ~/[redacted]/shreddit/Shreddit $ python setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-2571075.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python2.7/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.

[redactedUsername]@x1 ~/[redacted]/shreddit/Shreddit $ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to shreddit.egg-info/requires.txt
writing shreddit.egg-info/PKG-INFO
writing top-level names to shreddit.egg-info/top_level.txt
writing dependency_links to shreddit.egg-info/dependency_links.txt
writing entry points to shreddit.egg-info/entry_points.txt
reading manifest file 'shreddit.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'shreddit.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/shreddit
copying build/lib.linux-x86_64-2.7/shreddit/util.py -> build/bdist.linux-x86_64/egg/shreddit
copying build/lib.linux-x86_64-2.7/shreddit/__init__.py -> build/bdist.linux-x86_64/egg/shreddit
copying build/lib.linux-x86_64-2.7/shreddit/shredder.py -> build/bdist.linux-x86_64/egg/shreddit
copying build/lib.linux-x86_64-2.7/shreddit/shreddit.yml.example -> build/bdist.linux-x86_64/egg/shreddit
copying build/lib.linux-x86_64-2.7/shreddit/praw.ini.example -> build/bdist.linux-x86_64/egg/shreddit
copying build/lib.linux-x86_64-2.7/shreddit/app.py -> build/bdist.linux-x86_64/egg/shreddit
byte-compiling build/bdist.linux-x86_64/egg/shreddit/util.py to util.pyc
byte-compiling build/bdist.linux-x86_64/egg/shreddit/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/shreddit/shredder.py to shredder.pyc
byte-compiling build/bdist.linux-x86_64/egg/shreddit/app.py to app.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying shreddit.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying shreddit.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying shreddit.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying shreddit.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying shreddit.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying shreddit.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/shreddit-6.0.7-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing shreddit-6.0.7-py2.7.egg
Removing /usr/local/lib/python2.7/dist-packages/shreddit-6.0.7-py2.7.egg
Copying shreddit-6.0.7-py2.7.egg to /usr/local/lib/python2.7/dist-packages
shreddit 6.0.7 is already the active version in easy-install.pth
Installing shreddit script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/shreddit-6.0.7-py2.7.egg
Processing dependencies for shreddit==6.0.7
Searching for tornado==6.0.4
Best match: tornado 6.0.4
Processing tornado-6.0.4-py2.7-linux-x86_64.egg
tornado 6.0.4 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/tornado-6.0.4-py2.7-linux-x86_64.egg
Searching for six==1.15.0
Best match: six 1.15.0
Processing six-1.15.0-py2.7.egg
six 1.15.0 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/six-1.15.0-py2.7.egg
Searching for requests==2.23.0
Best match: requests 2.23.0
Processing requests-2.23.0-py2.7.egg
requests 2.23.0 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/requests-2.23.0-py2.7.egg
Searching for PyYAML==5.4.1
Best match: PyYAML 5.4.1
Processing PyYAML-5.4.1-py2.7-linux-x86_64.egg
PyYAML 5.4.1 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/PyYAML-5.4.1-py2.7-linux-x86_64.egg
Searching for praw==6.5.1
Best match: praw 6.5.1
Processing praw-6.5.1-py2.7.egg
praw 6.5.1 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/praw-6.5.1-py2.7.egg
Searching for backports-abc==0.5
Best match: backports-abc 0.5
Processing backports_abc-0.5-py2.7.egg
backports-abc 0.5 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/backports_abc-0.5-py2.7.egg
Searching for arrow==0.15.5
Best match: arrow 0.15.5
Processing arrow-0.15.5-py2.7.egg
arrow 0.15.5 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/arrow-0.15.5-py2.7.egg
Searching for urllib3==1.25.8
Best match: urllib3 1.25.8
Processing urllib3-1.25.8-py2.7.egg
urllib3 1.25.8 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/urllib3-1.25.8-py2.7.egg
Searching for idna==2.10
Best match: idna 2.10
Processing idna-2.10-py2.7.egg
idna 2.10 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/idna-2.10-py2.7.egg
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Processing chardet-3.0.4-py2.7.egg
chardet 3.0.4 is already the active version in easy-install.pth
Installing chardetect script to /usr/local/bin

Using /usr/local/lib/python2.7/dist-packages/chardet-3.0.4-py2.7.egg
Searching for certifi==2019.11.28
Best match: certifi 2019.11.28
Processing certifi-2019.11.28-py2.7.egg
certifi 2019.11.28 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/certifi-2019.11.28-py2.7.egg
Searching for websocket-client==0.57.0
Best match: websocket-client 0.57.0
Processing websocket_client-0.57.0-py2.7.egg
websocket-client 0.57.0 is already the active version in easy-install.pth
Installing wsdump.py script to /usr/local/bin

Using /usr/local/lib/python2.7/dist-packages/websocket_client-0.57.0-py2.7.egg
Searching for update-checker==0.16
Best match: update-checker 0.16
Processing update_checker-0.16-py2.7.egg
update-checker 0.16 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/update_checker-0.16-py2.7.egg
Searching for prawcore==1.0.1
Best match: prawcore 1.0.1
Processing prawcore-1.0.1-py2.7.egg
prawcore 1.0.1 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/prawcore-1.0.1-py2.7.egg
Searching for python-dateutil==2.8.1
Best match: python-dateutil 2.8.1
Processing python_dateutil-2.8.1-py2.7.egg
python-dateutil 2.8.1 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/python_dateutil-2.8.1-py2.7.egg
Searching for backports.functools-lru-cache==1.6.1
Best match: backports.functools-lru-cache 1.6.1
Processing backports.functools_lru_cache-1.6.1-py2.7.egg
backports.functools-lru-cache 1.6.1 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/backports.functools_lru_cache-1.6.1-py2.7.egg
Finished processing dependencies for shreddit==6.0.7
[redactedUsername]@x1 ~/[redacted]/shreddit/Shreddit $ shreddit -g
Traceback (most recent call last):
  File "/usr/local/bin/shreddit", line 11, in <module>
    load_entry_point('shreddit==6.0.7', 'console_scripts', 'shreddit')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/shreddit/app.py", line 10, in <module>
  File "build/bdist.linux-x86_64/egg/shreddit/shredder.py", line 6, in <module>
  File "/usr/local/lib/python2.7/dist-packages/praw-6.5.1-py2.7.egg/praw/__init__.py", line 14, in <module>
    from .reddit import Reddit  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/praw-6.5.1-py2.7.egg/praw/reddit.py", line 64
    def read_only(self) -> bool:
                        ^
SyntaxError: invalid syntax
[redactedUsername]@x1 ~/[redacted]/shreddit/Shreddit $ 
```

**Comment by pythonInRelay** [comment]
You have a permission issue with Linux. This is not related to the script at all.

**Comment by pythonInRelay** [comment]
Didn't follow the install instructions properly.

Closed.

**Comment by LinuxOnTheDesktop** [comment]
That is uncharitable, especially since, if I may put it this way, you cannot type.

**Comment by pythonInRelay** [comment]
> 
> 
> That is uncharitable, especially since, if I may put it this way, you cannot type.

What am I supposed to say?

Not only did you not follow all the instructions before opening this "issue". You even tried to install the script without sufficient write permissions and using the wrong version of Python and then even more stupidly you tried to get around this by installing as sudo (which anyone could have told you won't work). All the evidence is staring you right in the face. You could have at least checked the script before running it to see the requirements. You also have a partially borked installation left-over too.

If you don't know how to use Linux properly and don't wish to use the Github issue tracker for what it is intended, or don't understand how to use it either. I suggest you don't use either.

Maintaining this script doesn't automatically imply that I am writing a charity.

**Comment by pythonInRelay** [comment]
I actually have half a mind to post this on devRant or something similar because your accusation that I cannot type, when I maintain and improved this repo and dozens others, coupled with your own incompetence, and the notion that all of your repos are forks of other people's, is quite amusing.

**Comment by ggscott** [comment]
> That is uncharitable, especially since, if I may put it this way, you cannot type.

Your initial issue report you yourself typo'd the install line.  So this is quite amusing almost ironic.

**Comment by pythonInRelay** [comment]
> 
> 
> > That is uncharitable, especially since, if I may put it this way, you cannot type.
> 
> Your initial issue report you yourself typo'd the install line. So this is quite amusing almost ironic.

Wow, you're right. I actually missed that! 😂

**Comment by CSSmaiden** [comment]
>blind copy-paste

>can't install because no perms/broken python install

>literally given a readthedocs.io link by the console that explains the problem

>*oh I know, I'll just run it as sudo*

>still doesn't work

>"hey dude your script has **multiple** problems"

I literally facepalmed irl...
