### ISSUE TITLE
Unexpected status code 429

### ISSUE THREAD

**Issue by carolinering** [pythonInRelay/Shreddit#8]
After shreddit deletes 20-ish items, I get an error. Looks like HTTP 429 Too Many Requests -- I guess Reddit changed the rate-limiting threshold? Any fixes or workarounds?

Traceback below:

```
Traceback (most recent call last):
  File "/opt/anaconda3/bin/shreddit", line 33, in <module>
    sys.exit(load_entry_point('shreddit==6.0.7', 'console_scripts', 'shreddit')())
  File "/opt/anaconda3/lib/python3.8/site-packages/shreddit/app.py", line 45, in main
    shredder.shred()
  File "/opt/anaconda3/lib/python3.8/site-packages/shreddit/shredder.py", line 68, in shred
    deleted = self._remove_things(self._build_iterator())
  File "/opt/anaconda3/lib/python3.8/site-packages/shreddit/shredder.py", line 157, in _remove_things
    self._remove(item)
  File "/opt/anaconda3/lib/python3.8/site-packages/shreddit/shredder.py", line 137, in _remove
    self._remove_comment(item)
  File "/opt/anaconda3/lib/python3.8/site-packages/shreddit/shredder.py", line 124, in _remove_comment
    comment.edit(replacement_text)
  File "/opt/anaconda3/lib/python3.8/site-packages/praw/models/reddit/mixins/editable.py", line 20, in edit
    updated = self._reddit.post(API_PATH['edit'], data=data)[0]
  File "/opt/anaconda3/lib/python3.8/site-packages/praw/reddit.py", line 430, in post
    data = self.request('POST', path, data=data or {}, files=files,
  File "/opt/anaconda3/lib/python3.8/site-packages/praw/reddit.py", line 471, in request
    return self._core.request(method, path, data=data, files=files,
  File "/opt/anaconda3/lib/python3.8/site-packages/prawcore/sessions.py", line 173, in request
    return self._request_with_retries(
  File "/opt/anaconda3/lib/python3.8/site-packages/prawcore/sessions.py", line 126, in _request_with_retries
    assert response.status_code in self.SUCCESS_STATUSES, \
AssertionError: Unexpected status code: 429
```

**Comment by carolinering** [comment]
OK, well, it looks like Reddit fixed something on their end. It works now; I didn't change anything. Never mind!
